#! /bin/sh

# Colour palette from https://github.com/chriskempson/base16-xresources.

S_base00='#20201d'
S_base01='#292824'
S_base02='#6e6b5e'
S_base03='#7d7a68'
S_base04='#999580'
S_base05='#a6a28c'
S_base06='#e8e4cf'
S_base07='#fefbec'
S_base08='#d73737'
S_base09='#b65611'
S_base0A='#cfb017'
S_base0B='#60ac39'
S_base0C='#1fad83'
S_base0D='#6684e1'
S_base0E='#b854d4'
S_base0F='#d43552'

st -C "0:$S_base00" \
   -C "1:$S_base08" \
   -C "2:$S_base0B" \
   -C "3:$S_base0A" \
   -C "4:$S_base0D" \
   -C "5:$S_base0E" \
   -C "6:$S_base0C" \
   -C "7:$S_base05" \
   \
   -C "8:$S_base03" \
   -C "9:$S_base08" \
   -C "10:$S_base0B" \
   -C "11:$S_base0A" \
   -C "12:$S_base0D" \
   -C "13:$S_base0E" \
   -C "14:$S_base0C" \
   -C "15:$S_base07" \
   \
   -C "16:$S_base09" \
   -C "17:$S_base0F" \
   -C "18:$S_base01" \
   -C "19:$S_base02" \
   -C "20:$S_base04" \
   -C "21:$S_base06" \
   \
   -C "fg:$S_base05" \
   -C "bg:$S_base00" \
   -C "cs:$S_base05" \
   "$@"
