#! /bin/sh

# Colour palette from https://github.com/chriskempson/base16-xresources.

S_base00='#272822'
S_base01='#383830'
S_base02='#49483e'
S_base03='#75715e'
S_base04='#a59f85'
S_base05='#f8f8f2'
S_base06='#f5f4f1'
S_base07='#f9f8f5'
S_base08='#f92672'
S_base09='#fd971f'
S_base0A='#f4bf75'
S_base0B='#a6e22e'
S_base0C='#a1efe4'
S_base0D='#66d9ef'
S_base0E='#ae81ff'
S_base0F='#cc6633'

st -C "0:$S_base00" \
   -C "1:$S_base08" \
   -C "2:$S_base0B" \
   -C "3:$S_base0A" \
   -C "4:$S_base0D" \
   -C "5:$S_base0E" \
   -C "6:$S_base0C" \
   -C "7:$S_base05" \
   \
   -C "8:$S_base08" \
   -C "9:$S_base03" \
   -C "10:$S_base0B" \
   -C "11:$S_base0A" \
   -C "12:$S_base0D" \
   -C "13:$S_base0E" \
   -C "14:$S_base0C" \
   -C "15:$S_base07" \
   \
   -C "16:$S_base09" \
   -C "17:$S_base0F" \
   -C "18:$S_base01" \
   -C "19:$S_base02" \
   -C "20:$S_base04" \
   -C "21:$S_base06" \
   \
   -C "fg:$S_base05" \
   -C "bg:$S_base00" \
   -C "cs:$S_base05" \
   "$@"
