#! /bin/sh

# Common'
S_yellow='#b58900'
S_orange='#cb4b16'
S_red='#dc322f'
S_magenta='#d33682'
S_violet='#6c71c4'
S_blue='#268bd2'
S_cyan='#2aa198'
S_green='#859900'

# Dark
S_base03='#002b36'
S_base02='#073642'
S_base01='#586e75'
S_base00='#657b83'
S_base0='#839496'
S_base1='#93a1a1'
S_base2='#eee8d5'
S_base3='#fdf6e3'

# Light
#S_base03='#fdf6e3'
#S_base02='#eee8d5'
#S_base01='#93a1a1'
#S_base00='#839496'
#S_base0='#657b83'
#S_base1='#586e75'
#S_base2='#073642'
#S_base3='#002b36'

st -C "0:$S_base02" \
   -C "1:$S_red" \
   -C "2:$S_green" \
   -C "3:$S_yellow" \
   -C "4:$S_blue" \
   -C "5:$S_magenta" \
   -C "6:$S_cyan" \
   -C "7:$S_base2" \
   -C "9:$S_orange" \
   -C "8:$S_base03" \
   -C "10:$S_base01" \
   -C "11:$S_base00" \
   -C "12:$S_base0" \
   -C "13:$S_violet" \
   -C "14:$S_base1" \
   -C "15:$S_base3" \
   -C "bg:$S_base03" \
   -C "fg:$S_base0" \
   -C "cs:$S_base1" \
   "$@"
